Add russian translate
RobertSkalko/Mine-And-Slash-Rework pull request #80
Opened 2024-03-18 20:13 UTC by RikiDays

2024-03-18 23:45 UTC, SaloEater requested changes
Подозрительно сырой перевод. Пройдись сначала сам и поправь хотя бы все очевидные ошибки, а потом посмотрим еще раз

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.teleporter": "Картографическое устройство",
Сложно, скучно и главное непонятно.
В том же ПоЕ это слово перевели так
```suggestion
	"block.mmorpg.teleporter": "Машина картоходца",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +
А где потерял первые 3 строчки с советами по написанию перевода?

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.harvest.blue": "Прозрачные семена",
Я хоть и уже 60 часов вбухал в игру, все равно не понимаю что это за семена.
В старом переводе они переведены как "[Сияющие](https://github.com/RobertSkalko/Mine-And-Slash-Rework/blob/bf7fabf66ac8f61673a24a900281ea73ab75689a/src/main/resources/assets/mmorpg/lang/ru_ru.json#L6)", расскажешь почему именно прозрачные?

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.item_modifiable_in_station": "Можно использовать внутри модификационной станции для снаряжения",
Чем короче фраза тем проще имхо, я за старый вариант
```suggestion
	"mmorpg.tooltip.item_modifiable_in_station": "Можно использовать внутри станции модификации снаряжения",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.lootbox": "Что может быть внутри?",
Мои 5 копеек, опять чем короче тем имхо проще
```suggestion
	"mmorpg.tooltip.lootbox": "Что же внутри?",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.player_levelup": "Если ваша шкала опыта заполнена, используйте этот предмет для повышения уровня!",
Вопрос интересный, это именно полоса опыта (то что под хотбаром) или это именно уровень из мода? Если первое, то я бы оставил так
```suggestion
	"mmorpg.tooltip.player_levelup": "Если ваша полоса опыта заполнена, используйте этот предмет для повышения уровня!",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.capacitor": "Поместите в станцию ремонта, чтобы уменьшить потребление топлива.",
Судя по всему это именно обще-используемый термин в русском переводе
```suggestion
	"mmorpg.tooltip.capacitor": "Поместите в станцию починки, чтобы уменьшить потребление топлива.",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.socketable_item": "Этот самоцвет можно вставить в гнездо слота",
Или в крайнем случае гнездо предмета
```suggestion
	"mmorpg.tooltip.socketable_item": "Этот самоцвет можно вставить в гнездо",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.int": "Звездная пыль",
Надо придерживаться единобразия, чтобы везде было "<прилагательное> самоцвет"
```suggestion
	"item.mmorpg.jewel.int": "Звездный самоцвет",
```

Из других вариантов: Космический, Астральный, Небесный

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.unique_crafted": "Уникальный самоцвет Рунной мастерской",
```suggestion
	"item.mmorpg.jewel.unique_crafted": "Уникальный самоцвет рунического мастерства",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.stat_soul": "Душа характеристики снаряжения",
Я случайно задумался, а что вообще слово Stat делает в английском переводе. Вроде ни-ху-я, предлагаю убрать.
```suggestion
	"item.mmorpg.stat_soul": "Душа снаряжения",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.set_map": "Карта установки",
Это какая-то штука для разработчиков вроде как, я не разбирался особо, а слово "утилита" особо не переводится
```suggestion
	"item.mmorpg.set_map": "Утилита настройки карт",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.loot_bag": "Сумка добычи снаряжения",
К единому стилю
```suggestion
	"item.mmorpg.loot_bag": "Сумка со снаряжением",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.map_bag": "Сумка карт",
```suggestion
	"item.mmorpg.map_bag": "Сумка с картами",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.currency_bag": "Сумка валюты",
```suggestion
	"item.mmorpg.currency_bag": "Сумка с валютой",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.tutorial_book": "Учебник эпохи изгнания",
Хоть предмета в игре нет, я бы такие вещи называл пафосно
```suggestion
	"item.mmorpg.tutorial_book": "Учение об Эпохе Изгнания",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.map_back_portal": "Жемчуг отхода с карты",
Тут я сделал вывод что ты скорее всего сам не читал свой перевод, но если просто не знаешь английского, то тогда вопрос снимается (но тогда надо вдвойне ответственно подходить к этому вопросу)

Изменения тут оставляю на твою совесть
```suggestion
	"item.mmorpg.map_back_portal": "Жемчуг отхода с карты",
```

2024-03-18 23:45 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.mat.golden_orb": "Золотой сфер",
Ну это беспредел уже

2024-03-19 12:29 UTC, breadusofc requested changes
Это 100% переводил не человек.
Перепроверь профессии и заклинания.

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +    "mmorpg.stat.all_chaos_damage": "Хаос урон",
```suggestion
    "mmorpg.stat.all_chaos_damage": "Урон хаосом",
```
all_fire_damage - Огненный урон
all_chaos_damage - Урон хаосом

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +    "mmorpg.stat.all_elemental_damage": "Элементальный урон",
Чаще вижу, что переводят как стихии.

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.chaining_spell_dmg": "Урон от цепляющих заклинаний",
тег chaining говорит о том, что заклинание бьет **по цепи** (последовательно)

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.chance_of_blind": "§7Ваши §5☀ Хаос§7 Атаки имеют §a[VAL1]§7% шанс на наложение Слепоты",
```suggestion
	"mmorpg.stat.chance_of_blind": "§7Ваши атаки §5☀ Хаосом§7 имеют §a[VAL1]§7% шанс на наложение Слепоты",
```
(это не единственный случай)

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.chaos_mana_leech": "§7Поглощение §a[VAL1]§7% вашего §5☀ Хаос§7 Урона как маны",
```suggestion
	"mmorpg.stat.chaos_health_leech": "§7Поглощение §a[VAL1]§7% вашего Урона §5☀ Хаосом§7 как здоровья",
	"mmorpg.stat.chaos_mana_leech": "§7Поглощение §a[VAL1]§7% вашего Урона §5☀ Хаосом§7 как маны",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.phys_to_elemental": "Физический урон в урон стихиям",
```suggestion
	"mmorpg.stat.phys_to_elemental": "Физический урон в урон Стихиями",
```
С большой буквы пишу лишь потому, что в остальных подобных статах тип урона с большой

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.black_hole": "Призывает темную сферу, притягивающую ближайших врагов и наносящую [calc:black_hole]§5☀ Хаоса§7 урона при исчезновении.",
```suggestion
	"spell.desc.black_hole": "Призывает темную сферу, притягивающую ближайших врагов и наносящую [calc:black_hole] урона §5☀ Хаосом§7 при исчезновении.",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.chaos_totem": "Призывает тотем, вызывающий хаотические метеоры, наносящие [calc:chaos_totem] §5☀ Хаоса§7 урона в области.",
```suggestion
	"spell.desc.chaos_totem": "Призывает тотем, вызывающий хаотические метеоры, наносящие [calc:chaos_totem] урона §5☀ Хаосом§7 по области.",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.curse_of_weak": "Проклинает врагов Проклятием Слабости и наносит [calc:curse] §5☀ Хаоса§7 урона",
```suggestion
	"spell.desc.curse_of_agony": "Проклинает врагов Проклятием Агонии и наносит [calc:curse] урона §5☀ Хаосом§7",
	"spell.desc.curse_of_despair": "Проклинает врагов Проклятием Отчаяния и наносит [calc:curse] урона §5☀ Хаосом§7",
	"spell.desc.curse_of_weak": "Проклинает врагов Проклятием Слабости и наносит [calc:curse] урона §5☀ Хаосом§7",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.poison_trap": "Бросает ловушку, которая активируется при приближении врага, нанося [calc:ranger_trap]§5☀ Хаоса§7 урона в области вокруг себя.",
```suggestion
	"spell.desc.poison_ball": "Выбрасывает шар яда, нанося [calc:poisonball] урона §5☀ Хаосом§7",
	"spell.desc.poison_cloud": "Выбрасывает ядовитый газ, нанося [calc:poison_cloud] урона §5☀ Хаосом§7 ближайшим врагам.",
	"spell.desc.poison_trap": "Бросает ловушку, которая активируется при приближении врага, нанося [calc:ranger_trap] урона §5☀ Хаосом§7 в области вокруг себя.",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.spider_basic": "Базовая атака, наносящая [calc:spider_pet_basic] §5☀ Хаоса§7 урона одному врагу.",
```suggestion
	"spell.desc.spider_basic": "Базовая атака, наносящая [calc:spider_pet_basic] урона §5☀ Хаосом§7 одному врагу.",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.thorn_bush": "Призывает колючий куст, наносящий [calc:thorn_bush]§5☀ Хаоса§7 урона в области каждую секунду.",
```suggestion
	"spell.desc.thorn_bush": "Призывает колючий куст, наносящий [calc:thorn_bush] урона §5☀ Хаосом§7 в области каждую секунду.",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat_desc.all_water_damage": "Увеличивает всю наносимую урон водой, как заклинаниями, так и атаками.",
это как

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat_desc.ele_trident_damage": "Увеличивает элементарный урон, наносимый этим оружием.",
```suggestion
	"mmorpg.stat_desc.ele_atk_dmg": "Добавляет x урона от стихий при ударе оружием.",
	"mmorpg.stat_desc.ele_axe_damage": "Увеличивает урон от стихий, наносимый этим оружием.",
	"mmorpg.stat_desc.ele_bow_damage": "Увеличивает урон от стихий, наносимый этим оружием.",
	"mmorpg.stat_desc.ele_crossbow_damage": "Увеличивает урон от стихий, наносимый этим оружием.",
	"mmorpg.stat_desc.ele_pene": "Игнорирует столько сопротивления, это работает как вычитание.",
	"mmorpg.stat_desc.ele_resist": "Поглощает X процентов урона этого элемента.",
	"mmorpg.stat_desc.ele_staff_damage": "Увеличивает урон от стихий, наносимый этим оружием.",
	"mmorpg.stat_desc.ele_sword_damage": "Увеличивает урон от стихий, наносимый этим оружием.",
	"mmorpg.stat_desc.ele_trident_damage": "Увеличивает урон от стихий, наносимый этим оружием.",
```
урон стихиями, урон стихий, стихийный урон

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chest_type.harvest_purple_chest": "Сбор Фиолетового Сундука",
```suggestion
	"mmorpg.chest_type.harvest_blue_chest": "Голубой сундук Жатвы",
	"mmorpg.chest_type.harvest_green_chest": "Зелёный сундук Жатвы",
	"mmorpg.chest_type.harvest_purple_chest": "Фиолетовый сундук Жатвы",
```

2024-03-19 12:29 UTC, breadusofc commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.farming_triple_drop": "Шанс на тройной выпад",
дропы превратились в выпадения

2024-03-19 20:35 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.harvest.blue": "Прозрачные семена",
Измененно 

P.S. Изначальный перевод был для беты, а данный текст появился в новой версии, так что большинство строк не на своём месте

2024-03-19 20:36 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.item_modifiable_in_station": "Можно использовать внутри модификационной станции для снаряжения",
Как на счёт "Модифицируемый в станции для снаряжения"? более коректный перевод если судить по item_modifiable_in_station

2024-03-19 20:37 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.lootbox": "Что может быть внутри?",
Таким образом можно сделать ещё короче "Что внутри?" максимально коротко и ясно

2024-03-19 20:38 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.player_levelup": "Если ваша шкала опыта заполнена, используйте этот предмет для повышения уровня!",
Это моё виденье данного слова, всегда так говорил

2024-03-19 21:48 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.socketable_item": "Этот самоцвет можно вставить в гнездо слота",
Исправлено

2024-03-19 21:49 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.int": "Звездная пыль",
Исправлено

2024-03-19 21:50 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.unique_crafted": "Уникальный самоцвет Рунной мастерской",
Исправлено

2024-03-19 21:58 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.set_map": "Карта установки",
Исправлено

2024-03-19 21:59 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.stat_soul": "Душа характеристики снаряжения",
Изменено

2024-03-19 22:01 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.capacitor": "Поместите в станцию ремонта, чтобы уменьшить потребление топлива.",
Не считаю нужным. Только в случае если сама станция называется не станция ремонта, а станция починки

2024-03-19 22:02 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +
Измененно

P.S. Изначальный перевод был для беты, а данный текст появился в новой версии, так что большинство строк не на своём месте

2024-03-19 22:02 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.harvest.blue": "Прозрачные семена",
Исправлено

2024-03-19 22:06 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.map_bag": "Сумка карт",
Исправлено

2024-03-19 22:09 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.currency_bag": "Сумка валюты",
Исправлено

2024-03-19 22:09 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.tutorial_book": "Учебник эпохи изгнания",
Изменено

2024-03-19 22:10 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.map_back_portal": "Жемчуг отхода с карты",
С анлиским на самом деле не всё так хорошо, в следующих тестах решу нужны ли здесь правки

2024-03-19 22:11 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.mat.golden_orb": "Золотой сфер",
Исправлено

2024-03-19 22:14 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +    "mmorpg.stat.all_chaos_damage": "Хаос урон",
Судя по твоему комменту я не прошёл тест на робота

Исправлено

2024-03-19 22:14 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +    "mmorpg.stat.all_elemental_damage": "Элементальный урон",
Имеется ввиду "Урон стихиями"?

2024-03-19 22:16 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.chaining_spell_dmg": "Урон от цепляющих заклинаний",
Исправлено

P.S. Надеюсь данный перевод удовлетворит

2024-03-19 22:18 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.chance_of_blind": "§7Ваши §5☀ Хаос§7 Атаки имеют §a[VAL1]§7% шанс на наложение Слепоты",
Исправлено

2024-03-19 22:19 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.chaos_mana_leech": "§7Поглощение §a[VAL1]§7% вашего §5☀ Хаос§7 Урона как маны",
Исправлено

2024-03-19 22:27 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.phys_to_elemental": "Физический урон в урон стихиям",
Исправлено

2024-03-19 23:07 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.black_hole": "Призывает темную сферу, притягивающую ближайших врагов и наносящую [calc:black_hole]§5☀ Хаоса§7 урона при исчезновении.",
Исправлено

2024-03-19 23:09 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.chaos_totem": "Призывает тотем, вызывающий хаотические метеоры, наносящие [calc:chaos_totem] §5☀ Хаоса§7 урона в области.",
Исправлено

2024-03-19 23:09 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.curse_of_weak": "Проклинает врагов Проклятием Слабости и наносит [calc:curse] §5☀ Хаоса§7 урона",
Исправлено

2024-03-19 23:14 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.spider_basic": "Базовая атака, наносящая [calc:spider_pet_basic] §5☀ Хаоса§7 урона одному врагу.",
Исправлено

2024-03-19 23:14 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.poison_trap": "Бросает ловушку, которая активируется при приближении врага, нанося [calc:ranger_trap]§5☀ Хаоса§7 урона в области вокруг себя.",
Исправлено

2024-03-19 23:16 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"spell.desc.thorn_bush": "Призывает колючий куст, наносящий [calc:thorn_bush]§5☀ Хаоса§7 урона в области каждую секунду.",
Исправлено

2024-03-19 23:20 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat_desc.all_water_damage": "Увеличивает всю наносимую урон водой, как заклинаниями, так и атаками.",
Исправлено

2024-03-19 23:26 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat_desc.ele_trident_damage": "Увеличивает элементарный урон, наносимый этим оружием.",
Исправлено

2024-03-19 23:28 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chest_type.harvest_purple_chest": "Сбор Фиолетового Сундука",
Исправлено

2024-03-19 23:33 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.stat.farming_triple_drop": "Шанс на тройной выпад",
Исправлено

2024-03-19 23:35 UTC, RikiDays commented
P.S. Спасибо breadusofc и SaloEater за найдены ошибки, некоторые из них ещё обработаю но в целом большинство исправил

2024-03-20 11:34 UTC, RobertSkalko commented
This is the good way to do translation. PR, let others comment and fix stuff.

I'll just wait a day or two before the last comment and merge the PR to make sure everyone had time to comment

2024-03-21 17:34 UTC, RobertSkalko commented
Alright, any more edits will need a new PR

2024-03-21 17:34 UTC, merged