ru_ru
RobertSkalko/Mine-And-Slash-Rework pull request #85
Opened 2024-03-27 13:24 UTC by RikiDays

Patch 1.0.2

2024-03-28 08:05 UTC, SaloEater requested changes
After these changes will give it another look

2024-03-28 08:05 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chest_type.harvest_blue_chest": "Сбор Голубого Сундука",
Напомню https://github.com/RobertSkalko/Mine-And-Slash-Rework/pull/80#discussion_r1530255047

2024-03-28 08:05 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chest_type.support_gem": "Вспомогательный Самоцвет",
```suggestion
	"mmorpg.chest_type.support_gem": "Самоцвет поддержи",
```

2024-03-28 08:05 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.station.cooking": "Картографическое устройство",
Ну ты чего блин, меняй названия у всех станций

2024-03-28 13:15 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.station.cooking": "Картографическое устройство",
Исправлено

2024-03-28 13:15 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chest_type.support_gem": "Вспомогательный Самоцвет",
Исправлено

2024-03-28 13:15 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chest_type.harvest_blue_chest": "Сбор Голубого Сундука",
Исправлено

2024-03-28 18:48 UTC, SaloEater requested changes
Will add more after changes

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.station.alchemy": "Алихимическая станция",
Приводим к единому формату
```suggestion
	"block.mmorpg.station.alchemy": "Станция алхимика",
```

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"block.mmorpg.station.enchanting": "Модификационная станция",
Приводим к единому формату
```suggestion
	"block.mmorpg.station.enchanting": "Станция модификации",
```

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.item_modifiable_in_station": "Можно использовать внутри модификационной станции",
```suggestion
	"mmorpg.tooltip.item_modifiable_in_station": "Можно использовать внутри станции модификации",
```

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.lootbox": "Что внутри?",
Добавляем интригу
```suggestion
	"mmorpg.tooltip.lootbox": "Что же внутри?",
```

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.int": "Звездная пыль",
Долго думал, предлагаю так. И связь с космосом, и по цвету подходит
```suggestion
	"item.mmorpg.jewel.int": "Лунный самоцвет",
```
или поближе к оригиналу, но мне не так нравится
```suggestion
	"item.mmorpg.jewel.int": "Звездный самоцвет",
```

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.unique_crafted": "Уникальный самоцвет Рунной мастерской",
Верни обратно, руны - часть игры, а вот Рунной мастерской в игре нет

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.map_back_portal": "Жемчуг выходи из подземелья",
Ты опять невнимательно сам себя проверил, ппц
```suggestion
	"item.mmorpg.map_back_portal": "Жемчуг выхода из подземелья",
```

2024-03-28 18:48 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.mat.golden_orb": "Золотой сфер",
брух
```suggestion
	"item.mmorpg.mat.golden_orb": "Золотая сфера",
```

2024-03-28 19:23 UTC, SaloEater requested changes

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.arcane_staff": "Арканский посох",
```suggestion
	"mmorpg.affix.arcane_staff": "Волшебный посох",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.bone_helm": "Костяной обод",
```suggestion
	"mmorpg.affix.bone_helm": "Костяной шлем",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.mana_ring": "Кольцо пауа",
```suggestion
	"mmorpg.affix.mana_ring": "Кольцо маны",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.oakwood_staff": "Посох из дубовой древесины",
Не поверишь хд
```suggestion
	"mmorpg.affix.oakwood_staff": "Посох из дуба",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.already_casting": "Уже производится заклинание",
```suggestion
	"mmorpg.chat.already_casting": "Вы уже произносите заклинание",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_equip_that_many_supports": "Вы не можете экипировать столько поддерживающих самоцветов! Вы можете увеличить количество слотов, повысив уровень навыка.",
```suggestion
	"mmorpg.chat.cant_equip_that_many_supports": "Вы не можете экипировать столько самоцветов поддержки! Вы можете увеличить количество слотов, повысив уровень навыка.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_use_multiple_same_supports": "Нельзя использовать несколько одинаковых поддерживающих самоцветов.",
```suggestion
	"mmorpg.chat.cant_use_multiple_same_supports": "Нельзя использовать несколько одинаковых самоцветов поддержки.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cast_failed": "[Не удалось произвести заклинание]: ",
Поменяй, пожалуйста, везде где сможешь найти
```suggestion
	"mmorpg.chat.cast_failed": "[Не удалось произнести заклинание]: ",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.command_block_unavaliable": "Командные блоки отключены, это препятствует игре в Подземелья Mine and Slash!",
```suggestion
	"mmorpg.chat.command_block_unavaliable": "Командные блоки отключены, они мешают игре в подземельях Mine and Slash!",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_mns_weapon": "Вам нужно оружие Mine and Slash (Обладающее статистикой), чтобы произнести заклинания.",
Если я правильно понял, тут имеется ввиду, что нужно оружие из MnS, а его можно получить только после применения души снаряжения на любую вещь
```suggestion
	"mmorpg.chat.not_mns_weapon": "Вам нужно оружие Mine and Slash (Преобразовано душой), чтобы произнести заклинания.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.prof_output_slot_not_empty": "Нужен хотя бы 1 пустой слот вывода.",
Мне кажется это сюда подходит. Оно вроде пишется в чате, когда в станции нет места
```suggestion
	"mmorpg.chat.prof_output_slot_not_empty": "Нет места",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.soulless_gear_info": "Это снаряжение обездушено\nДуши снаряжения содержат статистику Mine and Slash\nБездушные предметы в основном бесполезны\nДуши создаются на станциях или выпадают из
Предлагаю везде использовать термин "характерстики" вместо "статистики" (Stat), когда мы работаем с этим контекстом
```suggestion
	"mmorpg.chat.soulless_gear_info": "Это снаряжение обездушено\nДуши снаряжения содержат характеристики Mine and Slash\nБездушные предметы в основном бесполезны\nДуши создаются на станциях или выпадают из мобов",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.be_unique": "Предмет должен быть уникальным по редкости.",
```suggestion
	"mmorpg.chat.be_unique": "Предмет должен быть уникальным.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_go_above": "Нельзя улучшить за пределы %1$s",
```suggestion
	"mmorpg.chat.cant_go_above": "Нельзя улучшить выше %1$s",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_same_buff": "У вас уже есть бафф такого типа.",
Давай уже по-славянски раз затеяли перевод
```suggestion
	"mmorpg.chat.cant_same_buff": "У вас уже есть усиление такого типа.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.destroys_output": "При помещении в Профессиональную Станцию с другими входами/материалами, все созданные рецепты будут приносить 3 раза больше опыта, но выход будет уничтожен.",
```suggestion
	"mmorpg.chat.destroys_output": "При помещении в любую Станцию все созданные рецепты будут приносить 3 раза больше опыта, но результат будет уничтожен.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.favor_down": "§cИз-за смерти ваша благосклонность упала до %1$s. Запомните это позором.",
```suggestion
	"mmorpg.chat.favor_down": "§cИз-за смерти ваша благосклонность упала до %1$s. Запомните этот позор.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.infuses_stats": "Насыщает характеристики пустой экипировки.",
```suggestion
	"mmorpg.chat.infuses_stats": "Насыщает пустую экипировку характеристиками.",
```

2024-03-28 19:23 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.needs_empty_or_rune": "Требуется пустое гнездо или руну внутри предмета. Если у предмета есть руна, она будет перекатана.",
```suggestion
	"mmorpg.chat.needs_empty_or_rune": "Требуется пустое гнездо или руна внутри предмета. Если в предмете уже есть руна, ее значения будут изменены случайным образом.",
```

2024-03-28 20:13 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.tooltip.lootbox": "Что внутри?",
да б............

2024-03-28 20:15 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.jewel.int": "Звездная пыль",
Исправлено

2024-03-28 20:16 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.map_back_portal": "Жемчуг выходи из подземелья",
Исправлено

2024-03-28 20:18 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"item.mmorpg.mat.golden_orb": "Золотой сфер",
исправлено

2024-03-28 20:21 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.mana_ring": "Кольцо пауа",
исправлено

2024-03-28 20:21 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.oakwood_staff": "Посох из дубовой древесины",
исправлено

2024-03-28 20:23 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.already_casting": "Уже производится заклинание",
Исправлено

2024-03-28 20:35 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_equip_that_many_supports": "Вы не можете экипировать столько поддерживающих самоцветов! Вы можете увеличить количество слотов, повысив уровень навыка.",
исправлено

2024-03-28 20:35 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_use_multiple_same_supports": "Нельзя использовать несколько одинаковых поддерживающих самоцветов.",
исправлено

2024-03-28 20:38 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cast_failed": "[Не удалось произвести заклинание]: ",
исправлено

2024-03-28 20:38 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.bone_helm": "Костяной обод",
изменено

2024-03-28 20:40 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.affix.arcane_staff": "Арканский посох",
исправлено

2024-03-28 20:41 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.command_block_unavaliable": "Командные блоки отключены, это препятствует игре в Подземелья Mine and Slash!",
изменено

2024-03-28 20:43 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_mns_weapon": "Вам нужно оружие Mine and Slash (Обладающее статистикой), чтобы произнести заклинания.",
изменено

2024-03-28 20:45 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.prof_output_slot_not_empty": "Нужен хотя бы 1 пустой слот вывода.",
Изменено

2024-03-28 21:06 UTC, SaloEater requested changes

2024-03-28 21:06 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_jewel": "Это не ювелирный предмет.",
Ты выше писал jewel - драгоценный камень, вот тут тоже именно про него речь
```suggestion
	"mmorpg.chat.not_jewel": "Это не самоцвет.",
```

2024-03-28 21:06 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_skillgem": "Это не навыковый камень.",
```suggestion
	"mmorpg.chat.not_skillgem": "Это не камень навыка.",
```

2024-03-28 21:06 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_owner": "§cВы не владелец этой станции.",
```suggestion
	"mmorpg.chat.not_owner": "§cЭто не ваша станция.",
```

2024-03-28 21:06 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.only_one_of_type": "Может быть только одно преимущество этого типа:",
Добавляю новый термин: Perk=Талант
```suggestion
	"mmorpg.chat.only_one_of_type": "Может быть только один талант этого типа:",
```

2024-03-28 21:06 UTC, SaloEater commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.prof_mat_dropguide": "Профессиональный материал Mine and Slash",
```suggestion
	"mmorpg.chat.prof_mat_dropguide": "Материал для профессий Mine and Slash",
```

2024-03-28 21:23 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.soulless_gear_info": "Это снаряжение обездушено\nДуши снаряжения содержат статистику Mine and Slash\nБездушные предметы в основном бесполезны\nДуши создаются на станциях или выпадают из
исправлено

2024-03-28 21:23 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.be_unique": "Предмет должен быть уникальным по редкости.",
изменено

2024-03-28 21:24 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_go_above": "Нельзя улучшить за пределы %1$s",
Не считаю нужным

2024-03-28 21:34 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.cant_same_buff": "У вас уже есть бафф такого типа.",
изменено

2024-03-28 21:38 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.destroys_output": "При помещении в Профессиональную Станцию с другими входами/материалами, все созданные рецепты будут приносить 3 раза больше опыта, но выход будет уничтожен.",
Исправлено

2024-03-28 21:38 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.favor_down": "§cИз-за смерти ваша благосклонность упала до %1$s. Запомните это позором.",
исправлен этот позор

2024-03-28 21:39 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.infuses_stats": "Насыщает характеристики пустой экипировки.",
исправлено

2024-03-28 21:42 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.needs_empty_or_rune": "Требуется пустое гнездо или руну внутри предмета. Если у предмета есть руна, она будет перекатана.",
исправлена

2024-03-28 21:43 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_jewel": "Это не ювелирный предмет.",
исправлено

2024-03-28 22:32 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_skillgem": "Это не навыковый камень.",
исправлено

2024-03-28 22:38 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.not_owner": "§cВы не владелец этой станции.",
Изменено

2024-03-28 22:39 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.only_one_of_type": "Может быть только одно преимущество этого типа:",
исправлено

2024-03-28 22:44 UTC, RikiDays commented on src/main/resources/assets/mmorpg/lang/ru_ru.json
> +	"mmorpg.chat.prof_mat_dropguide": "Профессиональный материал Mine and Slash",
изменено

2024-03-31 20:05 UTC, RobertSkalko commented
Looks finished, merging

2024-03-31 20:05 UTC, merged