Update zh_cn.json
RobertSkalko/Mine-And-Slash-Rework pull request #98
Opened 2024-06-18 06:26 UTC by golddan114

I have added Chinese translations for the dungeon map and prophecy panel
我针对地牢地图和预言面板的部分进行了补充汉化

2024-06-18 06:33 UTC, tang-bai approved these changes

2024-06-19 02:54 UTC, TUsama requested changes
标点符号记得连之前的那个PR一起改。还有你上一个PR有一些过于冗长的评论，你是翻译不是写mcmod资料，如果你想写，你就去那边写，别把资料一股脑塞进翻译里。

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.currency.map_rarity_upgrade": "地图属性提升宝珠",
rarity 应为稀有度，而非属性。

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"item.mmorpg.jewel.watcher_eye": "深渊之眼, 神圣珠宝",
应使用中文标点，包括你上个PR的那些修改也是。

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.chat.prophecy_altar_msg": "祭坛响应了你的接触（原句是这样2333）! (你现在可以打开你预言面板来选择并给自己施加一个诅咒)",
请移除个人评论。
请使用中文标点，并且括号内内容应该放在感叹号与中文之间，而非感叹号之后。即：
祭坛响应了你的接触（你现在可以打开你预言面板来选择并给自己施加一个诅咒）！
或者删去括号：
祭坛响应了你的接触，你现在可以打开你预言面板来选择并给自己施加一个诅咒！

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.prophecy_start.prophecy_unique": "独特预言等级（prophecy League unique）",
League 应为“赛季”，参见https://pathofexile.fandom.com/zh/wiki/League

这里不知道是不是指的该预言中会出现本赛季专属的独特装备

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.chat.no_more_lives_remaining": "你没有更多的生命（复活次数）来进入副本了.",
生命和复活次数可择一保留。

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.chat.prophecies_guide": "1) 被诅咒（拥有负面预言效果）时杀死地牢怪物以获得预言点数\n\n2)你可以在这个页面购买奖励\n\n3) 你受到的诅咒越多, 你获得的点数越多。\n\n你的点数和预言将会在进入另一张地牢地图时重置。",
coin 译为点数是出于何种考量？

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.league.uber": "Uber Boss Mechanic",
uber boss应为“终极头目”，参见https://poe.caimogu.cc/p/Uber_pinnacle_boss.html

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.cursed_by_weak": "\u00A77受到的元素虚弱诅咒",
weak应译为“易伤”

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.cursed_by_wounds": "\u00A77受到的受伤诅咒",
我没记错的话wound在我的译本（应该是1.15.2的）译为”流血“，指代一种Dot效果。这里用受伤指代Dot（如果这个是Dot的话）略微不妥，不太符合我国RPG游戏的惯常表述。

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.flat_physical_added_damage": "额外（Added）雷电伤害",
复制粘贴没改。

2024-06-19 02:54 UTC, TUsama commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.word.prophecyplayeraffix": "玩家获得（这个）负面效果:",
这个”这个“是什么意思？

2024-06-19 02:57 UTC, TUsama commented
还有你不要摇一些不知道哪来的账号来approve了，我知道你很想为项目做贡献，但是打铁也得自身硬，你现在做的这些还是有很多瑕疵的。

2024-06-19 03:23 UTC, golddan114 commented
> 还有你不要摇一些不知道哪来的账号来approve了，我知道你很想为项目做贡献，但是打铁也得自身硬，你现在做的这些还是有很多瑕疵的。

他原本的汉化就是那样，大佬可以去看一下，我们目前讨论的是这样的

2024-06-19 03:25 UTC, TUsama commented
哪样？这模组之前一直是我在弄，要不然我怎么知道相关的术语还有一致性问题。

2024-06-19 03:26 UTC, golddan114 commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.word.prophecyplayeraffix": "玩家获得（这个）负面效果:",
这个是原句的特殊指代，稍等我找一下

2024-06-19 03:27 UTC, TUsama commented
而且你那些句子的文法问题还有上个PR的某些物品的名称问题这些我都没有摘出来单独讲，毕竟你们也是花了心血的了。我这里提出的全都是硬伤，也就是格式以及一致性对的问题。

2024-06-19 03:27 UTC, golddan114 commented
> 还有你不要摇一些不知道哪来的账号来approve了，我知道你很想为项目做贡献，但是打铁也得自身硬，你现在做的这些还是有很多瑕疵的。

可以的话大佬可以帮忙更正一下，这个原本

> 哪样？这模组之前一直是我在弄，要不然我怎么知道相关的术语还有一致性问题。

新版本增加的诅咒部分我找不到参照，有不周到的地方十分抱歉

2024-06-19 03:28 UTC, TUsama commented
你是不知道怎么改这个PR吗？我见你好像是刚用Github没多久。

2024-06-19 03:28 UTC, golddan114 commented
稍等，我开个电脑

2024-06-19 03:29 UTC, golddan114 commented
> 你是不知道怎么改这个PR吗？我见你好像是刚用Github没多久。

就是为了做这个汉化才注册的，中间有好多小伙伴说没汉化看不懂，只能硬着头皮上了

2024-06-19 03:30 UTC, golddan114 commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.cursed_by_wounds": "\u00A77受到的受伤诅咒",
wound我搜了一下好像没有，之前那个版本的流血我没找到

2024-06-19 03:31 UTC, golddan114 commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.flat_physical_added_damage": "额外（Added）雷电伤害",
这个ADDED也没找到对应的，我不知道他是“增加”还是“再增长”

2024-06-19 03:31 UTC, golddan114 commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.cursed_by_wounds": "\u00A77受到的受伤诅咒",
我改一下。我没玩过1.15的

2024-06-19 03:32 UTC, TUsama commented
我建议你那边有需求的可以加一下909075947这个群，我汉化有更新第一时间是公布在这边。

2024-06-19 03:34 UTC, golddan114 commented
> 我建议你那边有需求的可以加一下909075947这个群，我汉化有更新第一时间是公布在这边。

好的

2024-06-19 03:35 UTC, golddan114 commented
> 909075947
申请了

2024-06-19 05:17 UTC, RobertSkalko commented
TUsama tell me if it's ready for merging in english please

2024-06-19 05:29 UTC, TUsama commented
got it

2024-06-19 08:42 UTC, closed without merging

2024-06-19 13:16 UTC, Thirace446 commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.cursed_by_wounds": "\u00A77受到的受伤诅咒",
> 我没有记错的话伤口在我的译本（应该是1.15.2的）译为”流血“，指代一种Dot效果。这里用受伤的指代Dot（如果这个是Dot的话）略微不太妥，不太符合我国RPG游戏的惯常表述。

bleed才是流血，造成物理伤害有概率施加流血dot
wounds是降低承受治疗效果的一个状态，在我的翻译里叫伤口

2024-06-19 13:22 UTC, Thirace446 commented on src/main/resources/assets/mmorpg/lang/zh_cn.json
> +	"mmorpg.stat.flat_physical_added_damage": "额外（Added）雷电伤害",
> 这个ADDED也没找到对应的，我不知道他是“增加”还是“再增长”

是额外附加，我在游戏里测试过了。
![20240619211828](https://github.com/RobertSkalko/Mine-And-Slash-Rework/assets/55902963/98ad1152-f09f-4b72-b3ed-d8295400bf59)
如果我的技能造成1000点物理伤害，我的辅助宝石带有72的雷电伤害，那么他会通过你的伤害乘区再造成一个雷电伤害。

2024-06-19 13:40 UTC, Thirace446 commented
> > 还有你不要摇一些不知道哪来的账号来approve了，我知道你很想为项目做贡献，但是打铁也得自身硬，你现在做的这些还是有很多瑕疵的。
> 
> 可以的话大佬可以帮忙更正一下，这个原本
> 
> > 哪样？这模组之前一直是我在弄，要不然我怎么知道相关的术语还有一致性问题。
> 
> 新版本增加的诅咒部分我找不到参照，有不周到的地方十分抱歉

所有的诅咒效果都在游戏内置的百科中有详细的描述，并且这些效果就是某些技能的效果，只不过是给玩家施加。
只要下几个本就明白了，做游戏翻译为什么不自己先玩一下游戏。